# Generated by Django 3.1.6 on 2021-06-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
