# Generated by Django 3.2.4 on 2021-08-30 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import lib.sitestuff


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('news', '0003_custom_create_divesites'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newspost',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_sites', lib.sitestuff.MyManager()),
            ],
        ),
        migrations.AddField(
            model_name='newspost',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
    ]
