# Generated by Django 3.2.4 on 2021-08-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_custom_migrate_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='divesite',
        ),
    ]
