# Generated by Django 3.2.7 on 2021-09-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_newspost_divesite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='topics',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=models.TextField(max_length=6000),
        ),
    ]
