# Generated by Django 3.2.4 on 2021-08-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_newspost_divesite'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiveSite',
        ),
    ]
